// flow-typed signature: 2585d3d34344ec86174d994431f86519
// flow-typed version: <<STUB>>/ajv_v5.2.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv' {
  declare module.exports: any;
}
