// flow-typed signature: 299e47ec57170f24107680c960ddcc27
// flow-typed version: <<STUB>>/babel-jest_v21.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-jest' {
  declare module.exports: any;
}
