// flow-typed signature: 46b87053ea90aef9b35c8f5ef953e96c
// flow-typed version: <<STUB>>/babel-eslint_v8.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
