// flow-typed signature: 5d0f32ee4a684306107ce79ddc581d2f
// flow-typed version: <<STUB>>/babel-plugin-flow-react-proptypes_v5.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-flow-react-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-flow-react-proptypes' {
  declare module.exports: any;
}
