// flow-typed signature: 2c99253ec98f4bc39955cdee3a0cfa2e
// flow-typed version: <<STUB>>/babel-preset-react-native_v3.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-native' {
  declare module.exports: any;
}
