// flow-typed signature: 989d609a938d45d4cf832007c2ace5ed
// flow-typed version: <<STUB>>/buffer_v5.0.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}
