// flow-typed signature: 38969249e0ffcd1464152a5a3809e1e7
// flow-typed version: <<STUB>>/bugsnag-react-native_v2.3.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-react-native' {
  declare module.exports: any;
}
