// flow-typed signature: e1c1c530d423d24f5a5a340189b5bf39
// flow-typed version: <<STUB>>/danger_v2.0.0-alpha.15/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger' {
  declare module.exports: any;
}
