// flow-typed signature: 755788b3e029da218f9e9e9c0ebfb764
// flow-typed version: <<STUB>>/delay_v2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'delay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'delay' {
  declare module.exports: any;
}
