// flow-typed signature: 76a362599a59d185488d58b97c46836f
// flow-typed version: <<STUB>>/eslint-plugin-react-native_v3.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-native' {
  declare module.exports: any;
}
