// flow-typed signature: aeb99093c40b8c87df77984cd6bf7561
// flow-typed version: <<STUB>>/eslint-config-prettier_v2.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
