// flow-typed signature: 8b981aacf743cfa0f090d1ca8ac10f58
// flow-typed version: <<STUB>>/eslint-plugin-flowtype_v2.36.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype' {
  declare module.exports: any;
}
