// flow-typed signature: 70b0e22c0ed21d311f8cc691179da728
// flow-typed version: <<STUB>>/eslint-plugin-react_v7.4.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
