// flow-typed signature: ae515e65d9d6326b7b37f7819b830a19
// flow-typed version: <<STUB>>/eslint_v4.7.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
