// flow-typed signature: cf5fe250ecc7af5cb0b66526fdc795bc
// flow-typed version: <<STUB>>/events_v1.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'events' {
  declare module.exports: any;
}
