// flow-typed signature: 09db72e11aaa4c18d9580c5fa1a095bd
// flow-typed version: <<STUB>>/get-urls_v7.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-urls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-urls' {
  declare module.exports: any;
}
