// flow-typed signature: 3dadf071b9310adbcbe80a1bdc65976e
// flow-typed version: <<STUB>>/html-entities_v1.2.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-entities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-entities' {
  declare module.exports: any;
}
