// flow-typed signature: 175173b49f7ee3a475e4473db99714fb
// flow-typed version: <<STUB>>/js-yaml_v3.10.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}
