// flow-typed signature: d677445297cebe844722432c589c5fff
// flow-typed version: <<STUB>>/junk_v2.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'junk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'junk' {
  declare module.exports: any;
}
