// flow-typed signature: d206ac07eaaf37a5e4055fd1021be0d0
// flow-typed version: <<STUB>>/moment-timezone_v0.5.13/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-timezone' {
  declare module.exports: any;
}
