// flow-typed signature: aa40e3cac30f5ca5a20e74320bdc8c64
// flow-typed version: <<STUB>>/prettier_v1.4.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
