// flow-typed signature: 33170193b83c010e9bbedd8ac3f92ae3
// flow-typed version: <<STUB>>/querystring_v0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystring' {
  declare module.exports: any;
}
