// flow-typed signature: 5953a26e9d7893cbde59d821b2fe737c
// flow-typed version: <<STUB>>/react-native-maps_v0.16.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}
