// flow-typed signature: 7e94c06ef4bf58cdc70447aac4f130e6
// flow-typed version: <<STUB>>/react-native-device-info_v0.11.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-device-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-device-info' {
  declare module.exports: any;
}
