// flow-typed signature: ba54e3090dea78b034f43eb939f7e9e6
// flow-typed version: <<STUB>>/react-native-restart_v0.0.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-restart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-restart' {
  declare module.exports: any;
}
