// flow-typed signature: e94785fcc454c9cd83c523ac37692b62
// flow-typed version: <<STUB>>/react-native-keychain_v2.0.0-rc/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keychain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keychain' {
  declare module.exports: any;
}
