// flow-typed signature: 83e5d35ca4fb6f88474f2ea248ab536d
// flow-typed version: <<STUB>>/react-native-onesignal_v3.0.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-onesignal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-onesignal' {
  declare module.exports: any;
}
