// flow-typed signature: 007bdc9e2376ace1d8461d4483c1fe89
// flow-typed version: <<STUB>>/react-native-calendar-events_v1.4.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-calendar-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-calendar-events' {
  declare module.exports: any;
}
