// flow-typed signature: cfdc79484749a53b97c5227535a636c5
// flow-typed version: <<STUB>>/react-test-renderer_v16.0.0-alpha.12/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}
