// flow-typed signature: 7198f74b9324bf914ec949538229f6e5
// flow-typed version: <<STUB>>/react-addons-shallow-compare_v15.6.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-shallow-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-shallow-compare' {
  declare module.exports: any;
}
