// flow-typed signature: 2a00b0ee79b4e4429e65c95411d46419
// flow-typed version: <<STUB>>/react-native-sortable-list_vgithub:hawkrives/react-native-sortable-list#7b72cc8e16cc71751836b49b3ea4bbc9e8e9cb99/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sortable-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sortable-list' {
  declare module.exports: any;
}
