// flow-typed signature: a748a775243c5f0e3dc76c4094e601ea
// flow-typed version: <<STUB>>/react-markdown_v2.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}
