// flow-typed signature: 266f331732a376f4d349d702cc299370
// flow-typed version: <<STUB>>/react-native-alphabetlistview_vgithub:sunnylqm/react-native-alphabetlistview#aea5d61fdd9034c7178d73ce8b2ee104da6941cc/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-alphabetlistview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-alphabetlistview' {
  declare module.exports: any;
}
