// flow-typed signature: 86cd3b885859ee0673f93823fad0140e
// flow-typed version: <<STUB>>/react-native-search-bar_v3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-search-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-search-bar' {
  declare module.exports: any;
}
