// flow-typed signature: 211c89a17da7040f9cf3682a237878f9
// flow-typed version: <<STUB>>/react-native-view-shot_v1.12.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-view-shot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-view-shot' {
  declare module.exports: any;
}
