// flow-typed signature: 9eb2cfd590741a554e65cd927f398155
// flow-typed version: <<STUB>>/react-native-communications_v2.2.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-communications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-communications' {
  declare module.exports: any;
}
