// flow-typed signature: 2f392ef5ffbefae807c290797e00d720
// flow-typed version: <<STUB>>/react-native-safari-view_v2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safari-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safari-view' {
  declare module.exports: any;
}
