// flow-typed signature: b2fe9a720ebdd59caf1fb91dc88bad79
// flow-typed version: <<STUB>>/react-native-google-analytics-bridge_v5.3.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-google-analytics-bridge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-google-analytics-bridge' {
  declare module.exports: any;
}
