// flow-typed signature: 8068a174f2b92d76c74f804f0244340c
// flow-typed version: <<STUB>>/react-native-network-info_v3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-network-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-network-info' {
  declare module.exports: any;
}
