// flow-typed signature: 18d69b7525ecbf82f3a630e69e2106fb
// flow-typed version: <<STUB>>/react-native-vector-icons_v4.4.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-vector-icons/Entypo' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Feather' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Foundation' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Octicons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module 'react-native-vector-icons/Zocial' {
  declare module.exports: any;
}
