// flow-typed signature: 50a02908d1468b2b52f72f515f964ed3
// flow-typed version: <<STUB>>/redux-logger_v3.0.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}
