// flow-typed signature: 7b5d7d3724f2053a70fa1c2e651c72ba
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}
