// flow-typed signature: ffbd62646220e9d6871f89ed1a9e276a
// flow-typed version: <<STUB>>/string-natural-compare_v2.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-natural-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-natural-compare' {
  declare module.exports: any;
}
