// flow-typed signature: ccbc83e314b8a5dc9163e0b9cbb1270a
// flow-typed version: <<STUB>>/timers_v0.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timers' {
  declare module.exports: any;
}
