// flow-typed signature: b544bb50946a3a9eaf8e4a1d15e29890
// flow-typed version: <<STUB>>/titlecase_v1.1.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'titlecase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'titlecase' {
  declare module.exports: any;
}
